/* tslint:disable */
/* eslint-disable */
/**
 * WorkoutTracker
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Exercise,
} from '../models/index';
import {
    ExerciseFromJSON,
    ExerciseToJSON,
} from '../models/index';

export interface CreateExerciseRequest {
    exercise: Exercise;
}

export interface DeleteExerciseRequest {
    id: string;
}

export interface GetExerciseByIdRequest {
    id: string;
}

export interface UpdateExerciseRequest {
    id: string;
    exercise: Exercise;
}

/**
 * 
 */
export class ExerciseApi extends runtime.BaseAPI {

    /**
     * Create exercise
     */
    async createExerciseRaw(requestParameters: CreateExerciseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.exercise === null || requestParameters.exercise === undefined) {
            throw new runtime.RequiredError('exercise','Required parameter requestParameters.exercise was null or undefined when calling createExercise.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/exercise`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExerciseToJSON(requestParameters.exercise),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create exercise
     */
    async createExercise(requestParameters: CreateExerciseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createExerciseRaw(requestParameters, initOverrides);
    }

    /**
     * Delete exercise
     */
    async deleteExerciseRaw(requestParameters: DeleteExerciseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteExercise.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/exercise/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete exercise
     */
    async deleteExercise(requestParameters: DeleteExerciseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteExerciseRaw(requestParameters, initOverrides);
    }

    /**
     * Get exercise by id
     */
    async getExerciseByIdRaw(requestParameters: GetExerciseByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Exercise>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getExerciseById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/exercise/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExerciseFromJSON(jsonValue));
    }

    /**
     * Get exercise by id
     */
    async getExerciseById(requestParameters: GetExerciseByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Exercise> {
        const response = await this.getExerciseByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all exercises
     */
    async getExercisesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Exercise>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/exercise`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExerciseFromJSON));
    }

    /**
     * Get all exercises
     */
    async getExercises(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Exercise>> {
        const response = await this.getExercisesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update exercise
     */
    async updateExerciseRaw(requestParameters: UpdateExerciseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateExercise.');
        }

        if (requestParameters.exercise === null || requestParameters.exercise === undefined) {
            throw new runtime.RequiredError('exercise','Required parameter requestParameters.exercise was null or undefined when calling updateExercise.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/exercise/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ExerciseToJSON(requestParameters.exercise),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update exercise
     */
    async updateExercise(requestParameters: UpdateExerciseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateExerciseRaw(requestParameters, initOverrides);
    }

}
