/* tslint:disable */
/* eslint-disable */
/**
 * WorkoutTracker
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ErrorResponse, Exercise } from '../models/index';
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  ExerciseFromJSON,
  ExerciseToJSON,
} from '../models/index';

export interface GetExercisesByNameRequest {
  exerciseName: string;
}

/**
 *
 */
export class ExerciseApi extends runtime.BaseAPI {
  /**
   * Get exercises by name
   */
  async getExercisesByNameRaw(
    requestParameters: GetExercisesByNameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Exercise>>> {
    if (
      requestParameters.exerciseName === null ||
      requestParameters.exerciseName === undefined
    ) {
      throw new runtime.RequiredError(
        'exerciseName',
        'Required parameter requestParameters.exerciseName was null or undefined when calling getExercisesByName.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/exercise/{exerciseName}`.replace(
          `{${'exerciseName'}}`,
          encodeURIComponent(String(requestParameters.exerciseName)),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ExerciseFromJSON),
    );
  }

  /**
   * Get exercises by name
   */
  async getExercisesByName(
    requestParameters: GetExercisesByNameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Exercise>> {
    const response = await this.getExercisesByNameRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
