/* tslint:disable */
/* eslint-disable */
/**
 * WorkoutTracker
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserMeasurement,
} from '../models/index';
import {
    UserMeasurementFromJSON,
    UserMeasurementToJSON,
} from '../models/index';

export interface CreateUserMeasurementRequest {
    userMeasurement: UserMeasurement;
}

export interface DeleteUserMeasurementRequest {
    userMeasurementId: string;
}

export interface GetUserMeasurementByIdRequest {
    userMeasurementId: string;
}

export interface UpdateUserMeasurementRequest {
    userMeasurementId: string;
    userMeasurement: UserMeasurement;
}

/**
 * 
 */
export class UserMeasurementApi extends runtime.BaseAPI {

    /**
     * Create user measurement
     */
    async createUserMeasurementRaw(requestParameters: CreateUserMeasurementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserMeasurement>> {
        if (requestParameters.userMeasurement === null || requestParameters.userMeasurement === undefined) {
            throw new runtime.RequiredError('userMeasurement','Required parameter requestParameters.userMeasurement was null or undefined when calling createUserMeasurement.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/usermeasurement`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserMeasurementToJSON(requestParameters.userMeasurement),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserMeasurementFromJSON(jsonValue));
    }

    /**
     * Create user measurement
     */
    async createUserMeasurement(requestParameters: CreateUserMeasurementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserMeasurement> {
        const response = await this.createUserMeasurementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete user measurement
     */
    async deleteUserMeasurementRaw(requestParameters: DeleteUserMeasurementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.userMeasurementId === null || requestParameters.userMeasurementId === undefined) {
            throw new runtime.RequiredError('userMeasurementId','Required parameter requestParameters.userMeasurementId was null or undefined when calling deleteUserMeasurement.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/usermeasurement/{userMeasurementId}`.replace(`{${"userMeasurementId"}}`, encodeURIComponent(String(requestParameters.userMeasurementId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete user measurement
     */
    async deleteUserMeasurement(requestParameters: DeleteUserMeasurementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteUserMeasurementRaw(requestParameters, initOverrides);
    }

    /**
     * Get user measurement by id
     */
    async getUserMeasurementByIdRaw(requestParameters: GetUserMeasurementByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserMeasurement>> {
        if (requestParameters.userMeasurementId === null || requestParameters.userMeasurementId === undefined) {
            throw new runtime.RequiredError('userMeasurementId','Required parameter requestParameters.userMeasurementId was null or undefined when calling getUserMeasurementById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/usermeasurement/{userMeasurementId}`.replace(`{${"userMeasurementId"}}`, encodeURIComponent(String(requestParameters.userMeasurementId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserMeasurementFromJSON(jsonValue));
    }

    /**
     * Get user measurement by id
     */
    async getUserMeasurementById(requestParameters: GetUserMeasurementByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserMeasurement> {
        const response = await this.getUserMeasurementByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all user measurements
     */
    async getUserMeasurementsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserMeasurement>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/usermeasurement`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserMeasurementFromJSON));
    }

    /**
     * Get all user measurements
     */
    async getUserMeasurements(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserMeasurement>> {
        const response = await this.getUserMeasurementsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update user measurement
     */
    async updateUserMeasurementRaw(requestParameters: UpdateUserMeasurementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserMeasurement>> {
        if (requestParameters.userMeasurementId === null || requestParameters.userMeasurementId === undefined) {
            throw new runtime.RequiredError('userMeasurementId','Required parameter requestParameters.userMeasurementId was null or undefined when calling updateUserMeasurement.');
        }

        if (requestParameters.userMeasurement === null || requestParameters.userMeasurement === undefined) {
            throw new runtime.RequiredError('userMeasurement','Required parameter requestParameters.userMeasurement was null or undefined when calling updateUserMeasurement.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/usermeasurement/{userMeasurementId}`.replace(`{${"userMeasurementId"}}`, encodeURIComponent(String(requestParameters.userMeasurementId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserMeasurementToJSON(requestParameters.userMeasurement),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserMeasurementFromJSON(jsonValue));
    }

    /**
     * Update user measurement
     */
    async updateUserMeasurement(requestParameters: UpdateUserMeasurementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserMeasurement> {
        const response = await this.updateUserMeasurementRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
