openapi: 3.0.0
info:
    title: WorkoutTracker
    version: 1.0.0


servers:
    - url: http://188.68.247.208:8080
      description: Local server

security:
    - basicAuth: []

tags:
    - name: user
      description: User operations
    - name: training
      description: Training operations
    - name: exercise
      description: Exercise operations



paths:
    /user:
        get:
            tags:
                - user
            summary: Get all users
            operationId: getUsers
            responses:
                '200':
                    description: A list of users
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/User'

    /user/{userId}:
        get:
            tags:
                - user
            summary: Get user by id
            operationId: getUserById
            parameters:
                - name: userId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: A user
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
        put:
            tags:
                - user
            summary: Update user
            operationId: updateUser
            parameters:
                - name: userId
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
            responses:
                '200':
                    description: User updated
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
        delete:
            tags:
                - user
            summary: Delete user
            operationId: deleteUser
            parameters:
                - name: userId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: User deleted
    /training:
        get:
            tags:
                - training
            summary: Get all trainings
            operationId: getTrainings
            responses:
                '200':
                    description: A list of trainings
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Training'
        post:
            tags:
                - training
            summary: Create training
            operationId: createTraining
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Training'
            responses:
                '200':
                    description: Training created
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Training'
    /training/{trainingId}:
        get:
            tags:
                - training
            summary: Get training by id
            operationId: getTrainingById
            parameters:
                - name: trainingId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: A training
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Training'
        put:
            tags:
                - training
            summary: Update training
            operationId: updateTraining
            parameters:
                - name: trainingId
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Training'
            responses:
                '200':
                    description: Training updated
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Training'
        delete:
            tags:
                - training
            summary: Delete training
            operationId: deleteTraining
            parameters:
                - name: trainingId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Training deleted
    /exercise:
        get:
            tags:
                - exercise
            summary: Get all exercises
            operationId: getExercises
            responses:
                '200':
                    description: A list of exercises
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Exercise'
        post:
            tags:
                - exercise
            summary: Create exercise
            operationId: createExercise
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Exercise'
            responses:
                '200':
                    description: Exercise created
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Exercise'
    /exercise/{exerciseId}:
        get:
            tags:
                - exercise
            summary: Get exercise by id
            operationId: getExerciseById
            parameters:
                - name: exerciseId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: An exercise
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Exercise'
        put:
            tags:
                - exercise
            summary: Update exercise
            operationId: updateExercise
            parameters:
                - name: exerciseId
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Exercise'
            responses:
                '200':
                    description: Exercise updated
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Exercise'
        delete:
            tags:
                - exercise
            summary: Delete exercise
            operationId: deleteExercise
            parameters:
                - name: exerciseId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Exercise deleted
    /usermeasurement:
        get:
            tags:
                - userMeasurement
            summary: Get all user measurements
            operationId: getUserMeasurements
            responses:
                '200':
                    description: A list of user measurements
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/UserMeasurement'
        post:
            tags:
                - userMeasurement
            summary: Create user measurement
            operationId: createUserMeasurement
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserMeasurement'
            responses:
                '200':
                    description: User measurement created
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserMeasurement'
    /usermeasurement/{userMeasurementId}:
        get:
            tags:
                - userMeasurement
            summary: Get user measurement by id
            operationId: getUserMeasurementById
            parameters:
                - name: userMeasurementId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: A user measurement
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserMeasurement'
        put:
            tags:
                - userMeasurement
            summary: Update user measurement
            operationId: updateUserMeasurement
            parameters:
                - name: userMeasurementId
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserMeasurement'
            responses:
                '200':
                    description: User measurement updated
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserMeasurement'
        delete:
            tags:
                - userMeasurement
            summary: Delete user measurement
            operationId: deleteUserMeasurement
            parameters:
                - name: userMeasurementId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: User measurement deleted

components:
    securitySchemes:
        basicAuth:
            type: http
            scheme: basic
    schemas:
        User:
            type: object
            properties:
                id:
                    type: string
                createdOn:
                    type: string
                modifiedOn:
                    type: string
                email:
                    type: string
                firstName:
                    type: string
                lastName:
                    type: string
                gender:
                    type: string
                    enum:
                        - MALE
                        - FEMALE
                        - OTHER
                userMeasurements:
                    type: array
                    items:
                        $ref: '#/components/schemas/UserMeasurement'
                trainings:
                    type: array
                    items:
                        $ref: '#/components/schemas/Training'
        UserMeasurement:
            type: object
            properties:
                id:
                    type: string
                createdOn:
                    type: string
                modifiedOn:
                    type: string
                weight:
                    type: number
                height:
                    type: number
                age:
                    type: number

                user:
                    $ref: '#/components/schemas/User'
        Training:
            type: object
            properties:
                id:
                    type: string
                createdOn:
                    type: string
                modifiedOn:
                    type: string
                name:
                    type: string
                description:
                    type: string
                exercises:
                    type: array
                    items:
                        $ref: '#/components/schemas/Exercise'
                trainingCategories:
                    type: array
                    items:
                        $ref: '#/components/schemas/TrainingCategory'
        Exercise:
            type: object
            properties:
                id:
                    type: string
                createdOn:
                    type: string
                modifiedOn:
                    type: string
                name:
                    type: string
                description:
                    type: string
                sets:
                    type: integer
                reps:
                    type: integer
                training:
                    $ref: '#/components/schemas/Training'
        TrainingCategory:
            type: string
            enum:
                - powerlifting
                - olympic weightlifting
                - cardio
                - stretching
                - other

