/* tslint:disable */
/* eslint-disable */
/**
 * WorkoutTracker
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TrainingCategory = {
    Powerlifting: 'powerlifting',
    OlympicWeightlifting: 'olympic weightlifting',
    Cardio: 'cardio',
    Stretching: 'stretching',
    Other: 'other'
} as const;
export type TrainingCategory = typeof TrainingCategory[keyof typeof TrainingCategory];


export function TrainingCategoryFromJSON(json: any): TrainingCategory {
    return TrainingCategoryFromJSONTyped(json, false);
}

export function TrainingCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingCategory {
    return json as TrainingCategory;
}

export function TrainingCategoryToJSON(value?: TrainingCategory | null): any {
    return value as any;
}

