/* tslint:disable */
/* eslint-disable */
/**
 * WorkoutTracker
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserMeasurementCreate
 */
export interface UserMeasurementCreate {
  /**
   *
   * @type {number}
   * @memberof UserMeasurementCreate
   */
  weight?: number;
  /**
   *
   * @type {number}
   * @memberof UserMeasurementCreate
   */
  arms?: number;
  /**
   *
   * @type {number}
   * @memberof UserMeasurementCreate
   */
  chest?: number;
  /**
   *
   * @type {number}
   * @memberof UserMeasurementCreate
   */
  belly?: number;
  /**
   *
   * @type {number}
   * @memberof UserMeasurementCreate
   */
  legs?: number;
}

/**
 * Check if a given object implements the UserMeasurementCreate interface.
 */
export function instanceOfUserMeasurementCreate(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UserMeasurementCreateFromJSON(
  json: any,
): UserMeasurementCreate {
  return UserMeasurementCreateFromJSONTyped(json, false);
}

export function UserMeasurementCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserMeasurementCreate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    weight: !exists(json, 'weight') ? undefined : json['weight'],
    arms: !exists(json, 'arms') ? undefined : json['arms'],
    chest: !exists(json, 'chest') ? undefined : json['chest'],
    belly: !exists(json, 'belly') ? undefined : json['belly'],
    legs: !exists(json, 'legs') ? undefined : json['legs'],
  };
}

export function UserMeasurementCreateToJSON(
  value?: UserMeasurementCreate | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    weight: value.weight,
    arms: value.arms,
    chest: value.chest,
    belly: value.belly,
    legs: value.legs,
  };
}
