/* tslint:disable */
/* eslint-disable */
/**
 * WorkoutTracker
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserMeasurement
 */
export interface UserMeasurement {
    /**
     * 
     * @type {string}
     * @memberof UserMeasurement
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserMeasurement
     */
    createdOn?: string;
    /**
     * 
     * @type {string}
     * @memberof UserMeasurement
     */
    modifiedOn?: string;
    /**
     * 
     * @type {number}
     * @memberof UserMeasurement
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof UserMeasurement
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof UserMeasurement
     */
    age?: number;
}

/**
 * Check if a given object implements the UserMeasurement interface.
 */
export function instanceOfUserMeasurement(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserMeasurementFromJSON(json: any): UserMeasurement {
    return UserMeasurementFromJSONTyped(json, false);
}

export function UserMeasurementFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMeasurement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdOn': !exists(json, 'createdOn') ? undefined : json['createdOn'],
        'modifiedOn': !exists(json, 'modifiedOn') ? undefined : json['modifiedOn'],
        'weight': !exists(json, 'weight') ? undefined : json['weight'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'age': !exists(json, 'age') ? undefined : json['age'],
    };
}

export function UserMeasurementToJSON(value?: UserMeasurement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdOn': value.createdOn,
        'modifiedOn': value.modifiedOn,
        'weight': value.weight,
        'height': value.height,
        'age': value.age,
    };
}

