/* tslint:disable */
/* eslint-disable */
/**
 * WorkoutTracker
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
  /**
   *
   * @type {string}
   * @memberof UserCreate
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof UserCreate
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof UserCreate
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof UserCreate
   */
  gender?: string;
  /**
   *
   * @type {number}
   * @memberof UserCreate
   */
  age?: number;
  /**
   *
   * @type {number}
   * @memberof UserCreate
   */
  height?: number;
}

/**
 * Check if a given object implements the UserCreate interface.
 */
export function instanceOfUserCreate(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UserCreateFromJSON(json: any): UserCreate {
  return UserCreateFromJSONTyped(json, false);
}

export function UserCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserCreate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: !exists(json, 'email') ? undefined : json['email'],
    firstName: !exists(json, 'firstName') ? undefined : json['firstName'],
    lastName: !exists(json, 'lastName') ? undefined : json['lastName'],
    gender: !exists(json, 'gender') ? undefined : json['gender'],
    age: !exists(json, 'age') ? undefined : json['age'],
    height: !exists(json, 'height') ? undefined : json['height'],
  };
}

export function UserCreateToJSON(value?: UserCreate | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    firstName: value.firstName,
    lastName: value.lastName,
    gender: value.gender,
    age: value.age,
    height: value.height,
  };
}
