name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Use Node.js'
        uses: actions/setup-node@v2

      - name: Npm install dependencies
        run: npm install

      - name: Typecheck
        run: npm typecheck

      - name: Lint
        run: npm lint

      - name: Build
        run: yarn build

      - name: Test
        run: npm test
